ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM cuba_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE USAGE, SELECT ON SEQUENCES FROM cuba_app;

REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM cuba_app;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM cuba_app;
REVOKE USAGE ON SCHEMA public FROM cuba_app;
